# Generated by Django 3.2.6 on 2021-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sell_topics', models.CharField(max_length=100)),
                ('buy_topics', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('study_topics', models.CharField(max_length=100)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('sell_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
